### ISSUE TITLE
[Bug] OctoPrint-PrettyGCode plugin wasn't reinstalled after the migration

### ISSUE THREAD

**Issue by pwr22** [cp2004/Octoprint-Upgrade-To-Py3#14]
**Describe the bug**
Upgrade went fine aside from losing this one plugin. It does support Python 3 and reinstalling manually has gone fine.

**Script output**
Sorry I've lost the output, but it was the latest version yesterday.

**Script version**
Sorry I've lost the output, but it was the latest version yesterday.

**OctoPrint Version**
OctoPrint 1.4.2

**Relevant plugins that may have caused errors**
OctoPrint-PrettyGCode

The only errors in the output were the benign ones from Octolapse in #6. 

**Additional information**
https://plugins.octoprint.org/plugins/PrettyGCode/

**Comment by jneilliii** [comment]
I had this same issue with a standard backup/restore operation last night outside of the upgrade script.

**Comment by cp2004** [comment]
Conflict of IDs in the plugin repository - internally it is `prettygcode`, repository it is `PrettyGCode`.

I've reached out to @Kragrathea in https://github.com/Kragrathea/OctoPrint-PrettyGCode/issues/68, just to let them know.

@jneilliii is it easier if you change the ID, since you've got write access to the plugin repo?

**Comment by jneilliii** [comment]
That was my mess up in reviewing the plugin so it probably would be easier to update the plugin repo.

**Comment by jneilliii** [comment]
For whatever reason it seems the json file is generated from the md filename and not the provided id in the template part. I just renamed the md file now and the json data is showing all lowercase.
