### ISSUE TITLE
[Bug] ibpython3.7-dev_3.7.3-2+deb10u2_armhf not found

### ISSUE THREAD

**Issue by ils15** [cp2004/Octoprint-Upgrade-To-Py3#49]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.7/libpython3.7-dev_3.7.3-2+deb10u2_armhf.deb  404  Not Found [IP: 93.93.128.193 80]
E: Failed to fetch http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.7/python3.7-dev_3.7.3-2+deb10u2_armhf.deb  404  Not Found 

i think you need to update script

**Comment by cp2004** [comment]
It doesn't change the installed Python version, it just uses the available Python install on your OS to convert OctoPrint's environment from Py2 => Py3. 

On OctoPi 0.17, the newest Python version available through the repositories is 3.7.3, so that's what it uses. Otherwise, you have to manually build it from the source and that is a *pain* to do and I'm not doing it in the script.

I might add `--allow-releaseinfo-change` to the script, so that the odd one-or-two it catches out don't have to worry about it.

**Comment by RobinTail** [comment]
@cp2004 

It seems that this option is not supported by my Raspberry Pi 

```
Updating package list...
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
ERROR: failed to update package list
Please try manually
```

**Comment by cp2004** [comment]
What is special about your raspberry pi compared to everyone else's? I'll need to know more about what you have installed.
